spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/athenadb'
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
server:
  error:
    include-message: always

